export const tags = {
  'oat-grass-roots': { id: 'oat-grass-roots', label: 'oat grass roots' },
  'coconut-fiber': { id: 'coconut-fiber', label: 'coconut fiber' },
  painted: { id: 'painted', label: 'painted' },
  'seed-pod': { id: 'seed-pod', label: 'seed pod' },
  stone: { id: 'stone', label: 'stone' },
  lamp: { id: 'lamp', label: 'lamp' },
  sculpture: { id: 'sculpture', label: 'sculpture' },
  shell: { id: 'shell', label: 'shell' },
  figure: { id: 'figure', label: 'figure' },
  object: { id: 'object', label: 'object' },
  translucent: { id: 'translucent', label: 'translucent' },
  wood: { id: 'wood', label: 'wood' },
  dowels: { id: 'dowels', label: 'dowels' },
  pyramid: { id: 'pyramid', label: 'pyramid' },
  nightlight: { id: 'nightlight', label: 'nightlight' },
  light: { id: 'light', label: 'light' },
  glow: { id: 'glow', label: 'glow' },
  stacked: { id: 'stacked', label: 'stacked' },
  surface: { id: 'surface', label: 'surface' },
  planes: { id: 'planes', label: 'planes' },
  vibration: { id: 'vibration', label: 'vibration' },
  architectural: { id: 'architectural', label: 'architectural' },
  carved: { id: 'carved', label: 'carved' },
  vertical: { id: 'vertical', label: 'vertical' },
  base: { id: 'base', label: 'base' },
  'found-material': { id: 'found-material', label: 'found material' },
  obelisk: { id: 'obelisk', label: 'obelisk' },
  coral: { id: 'coral', label: 'coral' },
  framing: { id: 'framing', label: 'framing' },
  ornament: { id: 'ornament', label: 'ornament' },
  provisional: { id: 'provisional', label: 'provisional' },
  narrative: { id: 'narrative', label: 'narrative' },
  mysticism: { id: 'mysticism', label: 'mysticism' },
  fabric: { id: 'fabric', label: 'fabric' },
  tapestry: { id: 'tapestry', label: 'tapestry' },
  grown: { id: 'grown', label: 'grown' },
  structure: { id: 'structure', label: 'structure' },
  orbital: { id: 'orbital', label: 'orbital' },
  planetary: { id: 'planetary', label: 'planetary' },
  swirl: { id: 'swirl', label: 'swirl' },
  mercuric: { id: 'mercuric', label: 'mercuric' },
  process: { id: 'process', label: 'process' },
  suspended: { id: 'suspended', label: 'suspended' },
  watchful: { id: 'watchful', label: 'watchful' },
  animate: { id: 'animate', label: 'animate' },
  tropical: { id: 'tropical', label: 'tropical' },
  color: { id: 'color', label: 'color' },
};

export function getTag(tagId) {
  return tags[tagId] ?? null;
}

export function getTagLabel(tagId) {
  return tags[tagId]?.label ?? tagId;
}
